apiVersion: batch/v1
kind: Job
metadata:
  name: ibm_anagrams-job
spec:
  template: 
    spec:
      containers: 
        -
          image: abagm/ibm-anagrams:latest
          name: ibm-anagrams-container
          volumeMounts:
            -
              mountPath: /data
              name: ibm-anagrams-volume
              readonly: true
      initContainers:
        -
          command:
            - sh
            - '-c'
            - 'set -x; cd /downloads; rm -f ${FILENAME}; wget ${URL}/${FILENAME}'
          env:
            -
              name: FILENAME
              valuefrom:
                secretKeyRef:
                  key: filename
                  name: ibm-anagrams-secret
            -
              name: URL
              valuefrom:
                secretKeyRef:
                  key: url
                  name: ibm-anagrams-secret
          image: busybox
          
